### PR TITLE
Update Polish.nam

### PR DESCRIPTION
**Pull request by DerDoktor82**
Add Grzegorz Brzęczyszczykiewicz

### CODE REVIEW

**Comment by MeridianOXC** [comment]
The file already contains the name Grzegorz. And what's the rationale behind adding the name Brzęczyszczykiewicz to xcom?

**Comment by DerDoktor82** [comment]
oh sorry. my bad about Grzegorz.
Grzegorz Brzęczyszczykiewicz is a famous polish "fun" name. It was used in a movie long time ago. It is that special because its hard to pronounce, especially for germans.
Thought it was a funny addition and i wanted to contribute something.

**Comment by MeridianOXC** [comment]
The thing is, it's too long. Only the shortest first name "Jan" fits on the screen together with this surname. All other combinations will be cut off.

**Comment by DerDoktor82** [comment]
ah i see. thank you. in that case lets revoke this case. 
Have a nice day.

**Pull request closed without merging**
